#!/bin/bash

VAR=$(pkg-config --help)

if ! [ "$?" -eq "0" ]; then
	echo "Must have pgk-config installed."
fi

g++ -std=c++17 $1 addressbook.pb.cc -o out $(pkg-config --cflags --libs protobuf) && ./out addressbook
